version: '3.1'
services:
  redis:
    image: 'redis'
    networks:
      - backend

  mongo:
    image: mongo:7.0.2
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '3020:3020'
    depends_on:
      - mongo
      - redis
    networks:
      - frontend
      - backend

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - 'GP_WEB_SERVER_PORT=3021'
      - 'GP_SERVER_BASE_URL=http://server:3020/'
    ports:
      - '3021:3021'
    depends_on:
      - server
    networks:
      - frontend

networks:
  frontend:
    name: frontend
  backend:
    name: backend
