version: 'version'
services:
  mongo:
    image: mongodb
    networks:
      - backend

  server:
    build: Dockerfile.server
    ports:
      - '3020:3020'
    depends_on:
      - mongo
    networks:
      - frontend
      - backend

  web:
    build: Dockerfile.web
    ports:
      - '3021:3021'
    depends_on:
      - server
    networks:
      - frontend

networks:
  frontend:
    name: gaia-frontend
  backend:
    name: gaia-frontend
