FROM node:18-bullseye AS base

WORKDIR /app

COPY package.json yarn.lock lerna.json nx.json ./

COPY packages/web/package.json packages/web/tsconfig.json packages/web/vue.config.js packages/web/babel.config.js packages/web/.browserslistrc ./packages/web/
COPY packages/web/src/ ./packages/web/src/

COPY packages/api/package.json packages/api/tsconfig.json ./packages/api/
COPY packages/api/src/ ./packages/api/src/

COPY packages/engine/package.json packages/engine/tsconfig.json ./packages/engine/
COPY packages/engine/src/ ./packages/engine/src/

RUN yarn && yarn build --scope @gaia-project/web

FROM nginx:stable-alpine

COPY packages/web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=base /app/packages/web/dist /usr/share/nginx/html

EXPOSE 3021
