FROM node:18-bullseye AS API

WORKDIR /app

COPY package.json yarn.lock lerna.json nx.json ./
COPY packages/api/package.json packages/api/tsconfig.json packages/api/codegen.ts packages/api/schema.graphql packages/api/codegen-gql-plugin.js ./packages/api/
COPY packages/api/src/ ./packages/api/src/
COPY packages/engine/package.json packages/engine/tsconfig.json ./packages/engine/
COPY packages/engine/src/ ./packages/engine/src/
COPY packages/web/package.json packages/web/tsconfig.json packages/web/vue.config.js packages/web/babel.config.js packages/web/.browserslistrc ./packages/web/
COPY packages/web/src/ ./packages/web/src/

RUN yarn

FROM node:18-alpine AS SERVER

COPY --from=API /app /app/

WORKDIR /app/packages/web/
ENTRYPOINT [ "yarn", "serve" ]
EXPOSE 3021
