export enum FactionType {
  Ambas = 'ambas',
  BalTaks = 'balTaks',
  Bescods = 'bescods',
  Firaks = 'firaks',
  Geodens = 'geodens',
  Gleens = 'gleens',
  HadschHallas = 'hadschHallas',
  Itars = 'itars',
  Ivits = 'ivits',
  Nevlas = 'nevlas',
  Lantids = 'lantids',
  Taklons = 'taklons',
  Terrans = 'terrans',
  Xenos = 'xenos',
}
